version: '3.9'
services:
    backend:
      build: ./backend
      command: python app/main.py
      tty: true
      volumes:
        - ./backend:/main
      environment:
        PYTHONPATH: .
        DATABASE_URL: 'sqlite:///./database.db'
      depends_on:
        - "postgres"

    frontend:
      build: ./frontend
      stdin_open: true
      volumes:
        - './frontend/src:/app'
      depends on:
        - server