FROM python:3.8.7

RUN pip install jwt
RUN pip install passlib
RUN pip install sqlalchemy
RUN pip install fastapi
RUN pip install pyjwt
RUN pip install uvicorn
RUN pip install python-multipart
RUN pip install pydantic
RUN pip install bcrypt

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .

EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

